name: Count Papers

on:
  push:
    branches: [ "main" ]

jobs:
  count_papers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Count *.md files
        run: |
          echo "Counting *.md files..."
          count=$(find . -name "*.md" ! -name "README.md" | wc -l)
          echo "Total Paper Count: $count"
